In [1]:
%pip install pandas numpy seaborn matplotlib klib dtale scikit-learn joblib

Requirement already satisfied: pandas in c:\users\asus\env\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\asus\env\lib\site-packages (2.3.3)
Requirement already satisfied: seaborn in c:\users\asus\env\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in c:\users\asus\env\lib\site-packages (3.10.6)
Requirement already satisfied: klib in c:\users\asus\env\lib\site-packages (1.3.2)
Requirement already satisfied: dtale in c:\users\asus\env\lib\site-packages (3.18.2)
Requirement already satisfied: scikit-learn in c:\users\asus\env\lib\site-packages (1.7.2)
Requirement already satisfied: joblib in c:\users\asus\env\lib\site-packages (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\asus\env\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\asus\env\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\asus\env\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\asus\env\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\env\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\asus\env\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\asus\env\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: jinja2>=3.1.0 in c:\users\asus\env\lib\site-packages (from klib) (3.1.6)
Requirement already satisfied: plotly>=5.11.0 in c:\users\asus\env\lib\site-packages (from klib) (6.5.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\asus\env\lib\site-packages (from klib) (1.15.3)
Requirement already satisfied: screeninfo>=0.8.1 in c:\users\asus\env\lib\site-packages (from klib) (0.8.1)
Requirement already satisfied: lz4 in c:\users\asus\env\lib\site-packages (from dtale) (4.4.5)
Requirement already satisfied: beautifulsoup4!=4.13.0b2 in c:\users\asus\env\lib\site-packages (from dtale) (4.13.5)
Requirement already satisfied: certifi in c:\users\asus\env\lib\site-packages (from dtale) (2025.10.5)
Requirement already satisfied: dash<=2.18.2 in c:\users\asus\env\lib\site-packages (from dtale) (2.18.2)
Requirement already satisfied: dash-bootstrap-components<=1.7.1 in c:\users\asus\env\lib\site-packages (from dtale) (1.7.1)
Requirement already satisfied: dash_daq<=0.5.0 in c:\users\asus\env\lib\site-packages (from dtale) (0.5.0)
Requirement already satisfied: et_xmlfile in c:\users\asus\env\lib\site-packages (from dtale) (2.0.0)
Requirement already satisfied: Flask in c:\users\asus\env\lib\site-packages (from dtale) (3.0.3)
Requirement already satisfied: Flask-Compress in c:\users\asus\env\lib\site-packages (from dtale) (1.23)
Requirement already satisfied: future>=0.14.0 in c:\users\asus\env\lib\site-packages (from dtale) (1.0.0)
Requirement already satisfied: itsdangerous in c:\users\asus\env\lib\site-packages (from dtale) (2.2.0)
Requirement already satisfied: kaleido in c:\users\asus\env\lib\site-packages (from dtale) (1.2.0)
Requirement already satisfied: missingno in c:\users\asus\env\lib\site-packages (from dtale) (0.5.2)
Requirement already satisfied: networkx in c:\users\asus\env\lib\site-packages (from dtale) (3.6)
Requirement already satisfied: openpyxl!=3.2.0b1 in c:\users\asus\env\lib\site-packages (from dtale) (3.1.5)
Requirement already satisfied: pkginfo in c:\users\asus\env\lib\site-packages (from dtale) (1.12.1.2)
Requirement already satisfied: requests in c:\users\asus\env\lib\site-packages (from dtale) (2.32.5)
Requirement already satisfied: squarify in c:\users\asus\env\lib\site-packages (from dtale) (0.4.4)
Requirement already satisfied: statsmodels in c:\users\asus\env\lib\site-packages (from dtale) (0.14.6)
Requirement already satisfied: strsimpy in c:\users\asus\env\lib\site-packages (from dtale) (0.2.1)
Requirement already satisfied: six in c:\users\asus\env\lib\site-packages (from dtale) (1.17.0)
Requirement already satisfied: werkzeug in c:\users\asus\env\lib\site-packages (from dtale) (3.0.6)
Requirement already satisfied: xarray in c:\users\asus\env\lib\site-packages (from dtale) (2025.12.0)
Requirement already satisfied: xlrd in c:\users\asus\env\lib\site-packages (from dtale) (2.0.2)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\asus\env\lib\site-packages (from dash<=2.18.2->dtale) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\asus\env\lib\site-packages (from dash<=2.18.2->dtale) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\asus\env\lib\site-packages (from dash<=2.18.2->dtale) (5.0.0)
Requirement already satisfied: importlib-metadata in c:\users\asus\env\lib\site-packages (from dash<=2.18.2->dtale) (8.7.1)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\asus\env\lib\site-packages (from dash<=2.18.2->dtale) (4.15.0)
Requirement already satisfied: retrying in c:\users\asus\env\lib\site-packages (from dash<=2.18.2->dtale) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\users\asus\env\lib\site-packages (from dash<=2.18.2->dtale) (1.6.0)
Requirement already satisfied: setuptools in c:\users\asus\env\lib\site-packages (from dash<=2.18.2->dtale) (80.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\asus\env\lib\site-packages (from Flask->dtale) (8.3.1)
Requirement already satisfied: blinker>=1.6.2 in c:\users\asus\env\lib\site-packages (from Flask->dtale) (1.9.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\asus\env\lib\site-packages (from werkzeug->dtale) (3.0.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\asus\env\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\asus\env\lib\site-packages (from beautifulsoup4!=4.13.0b2->dtale) (2.5)
Requirement already satisfied: colorama in c:\users\asus\env\lib\site-packages (from click>=8.1.3->Flask->dtale) (0.4.6)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\asus\env\lib\site-packages (from plotly>=5.11.0->klib) (2.15.0)
Requirement already satisfied: brotli in c:\users\asus\env\lib\site-packages (from Flask-Compress->dtale) (1.2.0)
Requirement already satisfied: backports.zstd in c:\users\asus\env\lib\site-packages (from Flask-Compress->dtale) (1.3.0)
Requirement already satisfied: zipp>=3.20 in c:\users\asus\env\lib\site-packages (from importlib-metadata->dash<=2.18.2->dtale) (3.23.0)
Requirement already satisfied: choreographer>=1.1.1 in c:\users\asus\env\lib\site-packages (from kaleido->dtale) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in c:\users\asus\env\lib\site-packages (from kaleido->dtale) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\asus\env\lib\site-packages (from kaleido->dtale) (3.11.5)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\asus\env\lib\site-packages (from kaleido->dtale) (2.4.0)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\asus\env\lib\site-packages (from choreographer>=1.1.1->kaleido->dtale) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in c:\users\asus\env\lib\site-packages (from pytest-timeout>=2.4.0->kaleido->dtale) (9.0.2)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\asus\env\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido->dtale) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\asus\env\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido->dtale) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in c:\users\asus\env\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido->dtale) (2.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asus\env\lib\site-packages (from requests->dtale) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\env\lib\site-packages (from requests->dtale) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\env\lib\site-packages (from requests->dtale) (2.5.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\asus\env\lib\site-packages (from statsmodels->dtale) (1.0.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df_train= pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\BigMart-Sales-Prediction-PFE\dataset\Train.csv')

In [5]:
df_train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [6]:
df_train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [8]:
df_train.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [9]:
df_train['Item_Weight'] = df_train['Item_Weight'].fillna(df_train['Item_Weight'].mean())

In [10]:
df_train.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [11]:
df_train['Outlet_Size'].value_counts()

Outlet_Size
Medium    2793
Small     2388
High       932
Name: count, dtype: int64

In [12]:
df_train['Outlet_Size'].mode()

0    Medium
Name: Outlet_Size, dtype: object

In [13]:
df_train['Outlet_Size'] = df_train['Outlet_Size'].fillna(df_train['Outlet_Size'].mode()[0])

In [14]:
df_train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,Medium,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [15]:
df_train.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [16]:
df_train.drop(['Item_Identifier','Outlet_Identifier'],axis=1,inplace=True)

In [17]:
import dtale

In [18]:
dtale.show(df_train)

In [19]:
import klib

In [20]:
klib.data_cleaning(df_train)

Shape of cleaned data: (8523, 10) - Remaining NAs: 0


Dropped rows: 0
     of which 0 duplicates. (Rows (first 150 shown): [])

Dropped columns: 0
     of which 0 single valued.     Columns: []
Dropped missing values: 0
Reduced memory by at least: 0.46 MB (-70.77%)

,item_weight,item_fat_content,item_visibility,item_type,item_mrp,outlet_establishment_year,outlet_size,outlet_location_type,outlet_type,item_outlet_sales
0,9.300000,Low Fat,0.016047,Dairy,249.809204,1999,Medium,Tier 1,Supermarket Type1,3735.137939
1,5.920000,Regular,0.019278,Soft Drinks,48.269199,2009,Medium,Tier 3,Supermarket Type2,443.422791
2,17.500000,Low Fat,0.016760,Meat,141.617996,1999,Medium,Tier 1,Supermarket Type1,2097.270020
3,19.200001,Regular,0.000000,Fruits and Vegetables,182.095001,1998,Medium,Tier 3,Grocery Store,732.380005
4,8.930000,Low Fat,0.000000,Household,53.861401,1987,High,Tier 3,Supermarket Type1,994.705200
...,...,...,...,...,...,...,...,...,...,...
8518,6.865000,Low Fat,0.056783,Snack Foods,214.521805,1987,High,Tier 3,Supermarket Type1,2778.383301
8519,8.380000,Regular,0.046982,Baking Goods,108.156998,2002,Medium,Tier 2,Supermarket Type1,549.284973
8520,10.600000,Low Fat,0.035186,Health and Hygiene,85.122398,2004,Small,Tier 2,Supermarket Type1,1193.113647
8521,7.210000,Regular,0.145221,Snack Foods,103.133202,2009,Medium,Tier 3,Supermarket Type2,1845.597656
8522,14.800000,Low Fat,0.044878,Soft Drinks,75.467003,1997,Small,Tier 1,Supermarket Type1,765.669983

In [21]:
klib.clean_column_names(df_train)

,item_weight,item_fat_content,item_visibility,item_type,item_mrp,outlet_establishment_year,outlet_size,outlet_location_type,outlet_type,item_outlet_sales
0,9.300,Low Fat,0.016047,Dairy,249.8092,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,5.920,Regular,0.019278,Soft Drinks,48.2692,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,17.500,Low Fat,0.016760,Meat,141.6180,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,1998,Medium,Tier 3,Grocery Store,732.3800
4,8.930,Low Fat,0.000000,Household,53.8614,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...
8518,6.865,Low Fat,0.056783,Snack Foods,214.5218,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,8.380,Regular,0.046982,Baking Goods,108.1570,2002,Medium,Tier 2,Supermarket Type1,549.2850
8520,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,7.210,Regular,0.145221,Snack Foods,103.1332,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,14.800,Low Fat,0.044878,Soft Drinks,75.4670,1997,Small,Tier 1,Supermarket Type1,765.6700

In [22]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   item_weight                8523 non-null   float64
 1   item_fat_content           8523 non-null   object
 2   item_visibility            8523 non-null   float64
 3   item_type                  8523 non-null   object
 4   item_mrp                   8523 non-null   float64
 5   outlet_establishment_year  8523 non-null   int64
 6   outlet_size                8523 non-null   object
 7   outlet_location_type       8523 non-null   object
 8   outlet_type                8523 non-null   object
 9   item_outlet_sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(5)
memory usage: 666.0+ KB

In [23]:
df_train=klib.convert_datatypes(df_train) # converts existing to more efficient dtypes, also called inside data_cleaning()
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   item_weight                8523 non-null   float32
 1   item_fat_content           8523 non-null   category
 2   item_visibility            8523 non-null   float32
 3   item_type                  8523 non-null   category
 4   item_mrp                   8523 non-null   float32
 5   outlet_establishment_year  8523 non-null   int16
 6   outlet_size                8523 non-null   category
 7   outlet_location_type       8523 non-null   category
 8   outlet_type                8523 non-null   category
 9   item_outlet_sales          8523 non-null   float32
dtypes: category(5), float32(4), int16(1)
memory usage: 192.9 KB

In [24]:
df_train

,item_weight,item_fat_content,item_visibility,item_type,item_mrp,outlet_establishment_year,outlet_size,outlet_location_type,outlet_type,item_outlet_sales
0,9.300000,Low Fat,0.016047,Dairy,249.809204,1999,Medium,Tier 1,Supermarket Type1,3735.137939
1,5.920000,Regular,0.019278,Soft Drinks,48.269199,2009,Medium,Tier 3,Supermarket Type2,443.422791
2,17.500000,Low Fat,0.016760,Meat,141.617996,1999,Medium,Tier 1,Supermarket Type1,2097.270020
3,19.200001,Regular,0.000000,Fruits and Vegetables,182.095001,1998,Medium,Tier 3,Grocery Store,732.380005
4,8.930000,Low Fat,0.000000,Household,53.861401,1987,High,Tier 3,Supermarket Type1,994.705200
...,...,...,...,...,...,...,...,...,...,...
8518,6.865000,Low Fat,0.056783,Snack Foods,214.521805,1987,High,Tier 3,Supermarket Type1,2778.383301
8519,8.380000,Regular,0.046982,Baking Goods,108.156998,2002,Medium,Tier 2,Supermarket Type1,549.284973
8520,10.600000,Low Fat,0.035186,Health and Hygiene,85.122398,2004,Small,Tier 2,Supermarket Type1,1193.113647
8521,7.210000,Regular,0.145221,Snack Foods,103.133202,2009,Medium,Tier 3,Supermarket Type2,1845.597656
8522,14.800000,Low Fat,0.044878,Soft Drinks,75.467003,1997,Small,Tier 1,Supermarket Type1,765.669983

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [26]:
df_train['item_fat_content']= le.fit_transform(df_train['item_fat_content'])
df_train['item_type']= le.fit_transform(df_train['item_type'])
df_train['outlet_size']= le.fit_transform(df_train['outlet_size'])
df_train['outlet_location_type']= le.fit_transform(df_train['outlet_location_type'])
df_train['outlet_type']= le.fit_transform(df_train['outlet_type'])

In [27]:
df_train

,item_weight,item_fat_content,item_visibility,item_type,item_mrp,outlet_establishment_year,outlet_size,outlet_location_type,outlet_type,item_outlet_sales
0,9.300000,1,0.016047,4,249.809204,1999,1,0,1,3735.137939
1,5.920000,2,0.019278,14,48.269199,2009,1,2,2,443.422791
2,17.500000,1,0.016760,10,141.617996,1999,1,0,1,2097.270020
3,19.200001,2,0.000000,6,182.095001,1998,1,2,0,732.380005
4,8.930000,1,0.000000,9,53.861401,1987,0,2,1,994.705200
...,...,...,...,...,...,...,...,...,...,...
8518,6.865000,1,0.056783,13,214.521805,1987,0,2,1,2778.383301
8519,8.380000,2,0.046982,0,108.156998,2002,1,1,1,549.284973
8520,10.600000,1,0.035186,8,85.122398,2004,2,1,1,1193.113647
8521,7.210000,2,0.145221,13,103.133202,2009,1,2,2,1845.597656
8522,14.800000,1,0.044878,14,75.467003,1997,2,0,1,765.669983

In [28]:
X=df_train.drop('item_outlet_sales',axis=1)

In [29]:
Y=df_train['item_outlet_sales']

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=101, test_size=0.2)

In [31]:
Y_test

8179     904.822205
8355    2795.694092
3411    1947.464966
7089     872.863770
6954    2450.144043
           ...
1317    1721.093018
4996     914.809204
531      370.184814
3891    1358.232056
6629    2418.185547
Name: item_outlet_sales, Length: 1705, dtype: float32

In [32]:
X.describe()

,item_weight,item_fat_content,item_visibility,item_type,item_mrp,outlet_establishment_year,outlet_size,outlet_location_type,outlet_type
count,8523.000000,8523.000000,8523.000000,8523.000000,8523.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,1.369354,0.066132,7.226681,140.992783,1997.831867,1.170832,1.112871,1.201220
std,4.226130,0.644810,0.051598,4.209990,62.275051,8.371760,0.600327,0.812757,0.796459
min,4.555000,0.000000,0.000000,0.000000,31.290001,1985.000000,0.000000,0.000000,0.000000
25%,9.310000,1.000000,0.026989,4.000000,93.826500,1987.000000,1.000000,0.000000,1.000000
50%,12.857645,1.000000,0.053931,6.000000,143.012802,1999.000000,1.000000,1.000000,1.000000
75%,16.000000,2.000000,0.094585,10.000000,185.643700,2004.000000,2.000000,2.000000,1.000000
max,21.350000,4.000000,0.328391,15.000000,266.888397,2009.000000,2.000000,2.000000,3.000000

In [33]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [34]:
X_train_std= sc.fit_transform(X_train)

In [35]:
X_test_std= sc.transform(X_test)

In [36]:
X_train_std

array([[ 1.52290023, -0.57382672,  0.68469731, ..., -1.95699503,
         1.08786619, -0.25964107],
       [-1.239856  , -0.57382672, -0.09514746, ..., -0.28872895,
        -0.13870429, -0.25964107],
       [ 1.54667619,  0.97378032, -0.0083859 , ..., -0.28872895,
        -0.13870429, -0.25964107],
       ...,
       [-0.08197109, -0.57382672, -0.91916229, ...,  1.37953713,
        -1.36527477, -0.25964107],
       [-0.74888436,  0.97378032,  1.21363045, ..., -0.28872895,
        -0.13870429, -0.25964107],
       [ 0.67885675, -0.57382672,  1.83915361, ..., -0.28872895,
         1.08786619,  0.98524841]], shape=(6818, 9))

In [37]:
X_test_std

array([[-0.43860916, -0.57382672, -0.21609253, ..., -0.28872895,
         1.08786619,  0.98524841],
       [ 1.22570184, -0.57382672, -0.52943464, ..., -1.95699503,
         1.08786619, -0.25964107],
       [-1.2184578 ,  0.97378032,  0.16277341, ...,  1.37953713,
        -1.36527477, -0.25964107],
       ...,
       [ 0.65508101, -0.57382672,  0.8782423 , ..., -0.28872895,
         1.08786619, -1.50453056],
       [ 1.01171909, -0.57382672, -1.28409256, ..., -0.28872895,
         1.08786619,  0.98524841],
       [-1.56558541,  0.97378032, -1.09265374, ..., -0.28872895,
        -0.13870429, -0.25964107]], shape=(1705, 9))

In [38]:
import joblib

In [39]:
joblib.dump(sc,r'C:\Users\ASUS\OneDrive\Desktop\BigMart-Sales-Prediction-PFE\models\sc.sav')

['C:\\Users\\ASUS\\OneDrive\\Desktop\\BigMart-Sales-Prediction-PFE\\models\\sc.sav']

In [40]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()

In [41]:
lr.fit(X_train_std,Y_train)

LinearRegression()

In [42]:
X_test.head()

,item_weight,item_fat_content,item_visibility,item_type,item_mrp,outlet_establishment_year,outlet_size,outlet_location_type,outlet_type
8179,11.000000,1,0.055163,8,100.335800,2009,1,2,2
8355,18.000000,1,0.038979,13,148.641800,1987,0,2,1
3411,7.720000,2,0.074731,1,77.598602,1997,2,0,1
7089,20.700001,1,0.049035,6,39.950600,2007,1,1,1
6954,7.550000,1,0.027225,3,152.934006,2002,1,1,1

In [43]:
Y_pred_lr=lr.predict(X_test_std)
Y_pred_lr

array([2046.00728016, 2130.35742269, 1207.94498753, ..., 1279.28266863,
       2360.54639912, 2351.11205438], shape=(1705,))

In [44]:
Y_test

8179     904.822205
8355    2795.694092
3411    1947.464966
7089     872.863770
6954    2450.144043
           ...
1317    1721.093018
4996     914.809204
531      370.184814
3891    1358.232056
6629    2418.185547
Name: item_outlet_sales, Length: 1705, dtype: float32

In [45]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [46]:
print(r2_score(Y_test,Y_pred_lr))
print(mean_absolute_error(Y_test,Y_pred_lr))
print(np.sqrt(mean_squared_error(Y_test,Y_pred_lr)))

0.504187577927004
880.99990440845
1162.4412631603452

In [47]:
from sklearn.ensemble import RandomForestRegressor
rf= RandomForestRegressor(n_estimators=1000)

In [48]:
rf.fit(X_train_std,Y_train)

RandomForestRegressor(n_estimators=1000)

In [49]:
Y_pred_rf= rf.predict(X_test_std)

In [50]:
print(r2_score(Y_test,Y_pred_rf))
print(mean_absolute_error(Y_test,Y_pred_rf))
print(np.sqrt(mean_squared_error(Y_test,Y_pred_rf)))

0.54790812996329
782.0638182847881
1110.006864655773

In [51]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RepeatedKFold, GridSearchCV

# 1. Définition du modèle AVEC LIMITES
# n_jobs=1 : Important pour ne pas surcharger le processeur
# max_depth=10 : CRUCIAL. Cela empêche les arbres de devenir trop gros et de manger toute la RAM.
model = RandomForestRegressor(random_state=42, n_jobs=1, max_depth=10)

# 2. Définition des paramètres à tester
# On commence petit. Si ça marche, vous pourrez tester [50, 100] plus tard.
n_estimators = [100, 1000] 

grid = dict(n_estimators=n_estimators)

# 3. Cross-Validation (Régression)
cv = RepeatedKFold(n_splits=3, n_repeats=1, random_state=101) # Réduit à 3 splits pour aller plus vite

# 4. Grid Search
grid_search_forest = GridSearchCV(estimator=model, 
                                  param_grid=grid, 
                                  n_jobs=1,           # Toujours 1 pour la sécurité mémoire
                                  scoring='r2', 
                                  error_score='raise', 
                                  verbose=2, 
                                  cv=cv)

print("Début de l'entraînement (Version optimisée mémoire)...")
# 5. Entraînement
grid_search_forest.fit(X_train_std, Y_train)

# 6. Résultats
print(f"Best: {grid_search_forest.best_score_:.3f} using {grid_search_forest.best_params_}")
means = grid_search_forest.cv_results_['mean_test_score']
stds = grid_search_forest.cv_results_['std_test_score']
params = grid_search_forest.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
    print(f"{mean:.3f} ({stdev:.3f}) with: {param}")

Début de l'entraînement (Version optimisée mémoire)...
Fitting 3 folds for each of 2 candidates, totalling 6 fits
[CV] END ...................................n_estimators=100; total time=   2.8s
[CV] END ...................................n_estimators=100; total time=   2.9s
[CV] END ...................................n_estimators=100; total time=   2.8s
[CV] END ..................................n_estimators=1000; total time=  30.5s
[CV] END ..................................n_estimators=1000; total time=  27.9s
[CV] END ..................................n_estimators=1000; total time=  28.3s
Best: 0.580 using {'n_estimators': 1000}
0.579 (0.016) with: {'n_estimators': 100}
0.580 (0.016) with: {'n_estimators': 1000}

In [52]:
grid_search_forest.best_params_

{'n_estimators': 1000}

In [53]:
grid_search_forest.best_score_

np.float64(0.5802945813951427)

In [54]:
Y_pred_rf_grid=grid_search_forest.predict(X_test_std)

In [55]:
Y_pred_rf_grid

array([1609.27699865, 2699.92217677, 1353.44081661, ...,  411.1141965 ,
       1679.36952205, 2358.58692921], shape=(1705,))

In [56]:
r2_score(Y_test,Y_pred_rf_grid)

0.5830246023424445

In [57]:
import joblib

In [58]:
joblib.dump(grid_search_forest,r'C:\Users\ASUS\OneDrive\Desktop\BigMart-Sales-Prediction-PFE\models\random_forest_grid.joblib')

['C:\\Users\\ASUS\\OneDrive\\Desktop\\BigMart-Sales-Prediction-PFE\\models\\random_forest_grid.joblib']

In [59]:
joblib.dump(lr,r'C:\Users\ASUS\OneDrive\Desktop\BigMart-Sales-Prediction-PFE\models\linearRegresion.joblib')

['C:\\Users\\ASUS\\OneDrive\\Desktop\\BigMart-Sales-Prediction-PFE\\models\\linearRegresion.joblib']